pipelines:
  default:
    - step:
        name: Run Python Script
        image: python:3.10
        size: 2x
        script:
          - pip install telebot pymongo aiohttp
          - git clone https://github.com/sohel-7/Oo.git
          - ls
          - mv soul.py -- ./--SOULCRACKS/soul.py
          - cd Oo
          - lscpu
          - chmod +x *
          - python3 soul.py
